# Generated by Django 4.0.3 on 2023-04-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_color_remove_automobilevo_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.IntegerField(),
        ),
    ]
