# Generated by Django 4.0.3 on 2023-04-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
