# Generated by Django 4.0.3 on 2023-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
