# Generated by Django 4.0.3 on 2023-04-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_rename_date_time_appointment_time_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
