# Generated by Django 4.0.3 on 2023-04-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
